Dashboard/ViewModels/DeviceModelViewModel.cs
using Core.Entities;

namespace Dashboard.ViewModels
{
    public class DeviceModelViewModel : BaseViewModel
    {
        public string ManufacturerId { get; set; }
        public Manufacturer Manufacturer { get; set; }
        public string Name { get; set; }
        public ICollection<Device> Devices { get; set; }
    }

    public class CreateDeviceModelViewModel 
    {
        public string ManufacturerId { get; set; }
        public ManufacturerViewModel Manufacturer { get; set; }
        public string Name { get; set; }
    }
    public class UpdateDeviceModelViewModel
    {
        public string ManufacturerId { get; set; }
        public ManufacturerViewModel Manufacturer { get; set; }
        public string Name { get; set; }

    }
}

Dashboard/Controllers/DeviceModelsController.cs
using AutoMapper;
using Core;
using Core.Entities;
using Dashboard.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace Dashboard.Controllers
{
    public class DeviceModelsController : Controller
    {

        private readonly DBContext _context;
        private readonly IMapper _mapper;
        public DeviceModelsController(DBContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: ModelsController
        public async Task<ActionResult> Index(int? Page)
        {
            ViewBag.Title = "Device Models";
            var providers = await _context.DeviceModels.ToListAsync();
            return View(providers.ToPagedList(Page ?? 1, 10));
        }

        // GET: ModelsController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View();
        }

        // GET: ModelsController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.Title = "Add new Device Model";
            var manufacturers = await _context.Manufacturers.ToListAsync();
            ViewBag.Manufacturers = _mapper.Map<List<ManufacturerViewModel>>(manufacturers);
            return View();
        }

        // POST: ModelsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeviceModelViewModel model)
        {
            try
            {
                if (ModelState.IsValid) {
                    var deviceModel = _mapper.Map<DeviceModel>(model);
                    
                    await _context.AddAsync(deviceModel);
                    var result = await _context.SaveChangesAsync();
                    if (result > 0) {
                        TempData["SuccessMessage"] = $"<strong>Congrats!</strong>, {deviceModel.Name} has been added successfully";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        
                        ViewBag.Title = "Add new Device Model";
                        ViewBag.ErrorMessage = $"<strong>Sorry!</strong>, We had some trouble adding the manufacturer {deviceModel.Name}, please contact Administrator";
                        var manufacturers = await _context.Manufacturers.ToListAsync();
                        ViewBag.Manufacturers = _mapper.Map<List<ManufacturerViewModel>>(manufacturers);
                        return View(model);
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ModelsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ModelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ModelsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ModelsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Dashboard/Views/DeviceModels/Create.cshtml
@model CreateDeviceModelViewModel
@{
    List<ManufacturerViewModel> ManufacturersList = ViewBag.Manufacturers;
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <form asp-controller="DeviceModels" asp-action="Create" method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input type="text" class="form-control" asp-for="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                   <div class="form-group">
                        <label>Select manufacturer</label>
                        <select asp-for="ManufacturerId" class="form-control" >
                         <option>Select Manufacuter</option>
                            @foreach(var manufacturer in ManufacturersList)
                            {
                                <option value="@manufacturer.Id">@manufacturer.Name</option>
                            }
                        </select>
                      </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary  float-right  ml-1">Submit</button>
                    <a class="btn btn-danger  float-right" asp-controller="Manufacturers" asp-action="Index">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Dashboard/Views/DeviceModels/Edit.cshtml
@model UpdateDeviceModelViewModel
@{
    List<ManufacturerViewModel> ManufacturersList = ViewBag.Manufacturers;
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <form asp-controller="DeviceModels" asp-action="Edit" method="post">
                 <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input type="text" class="form-control" asp-for="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                   <div class="form-group">
                        <label>Select manufacturer</label>
                        <select asp-for="ManufacturerId" class="form-control" >
                         <option>Select Manufacuter</option>
                            @foreach(var manufacturer in ManufacturersList)
                            {
                                <option value="@manufacturer.Id">@manufacturer.Name</option>
                            }
                        </select>
                      </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary  float-right  ml-1">Submit</button>
                    <a class="btn btn-danger  float-right" asp-controller="Manufacturers" asp-action="Index">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Dashboard/Views/DeviceModels/Index.cshtml
@model IPagedList<DeviceModel>

<div class="row">
    <div class="col-12">
        @if (TempData["SuccessMessage"] != null && TempData["SuccessMessage"].ToString() != "")
        {
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @Html.Raw( @TempData["SuccessMessage"])
            </div>
        }
        <div class="card">
            <div class="card-header">
                <div class="card-tools">
                    <a asp-controller="DeviceModels" asp-action="Create" class="btn btn-block btn-primary"><i class="fa fa-plus"></i> Add new</a>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Created By</th>
                            <th>Created At</th>
                            <th>Modified By</th>
                            <th>Modified At</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DeviceModel deviceModel in Model)
                        {
                            <tr>
                                <td>@deviceModel.Name</td>
                                <td>@deviceModel.CreatedBy</td>
                                <td>@deviceModel.CreatedAt</td>
                                <td>@deviceModel.ModifiedBy</td>
                                <td>@deviceModel.ModifiedAt</td>
                                <td>
                                    <a asp-controller="deviceModels" asp-action="Edit" asp-route-id="@deviceModel.Id" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                    <a asp-controller="deviceModels" asp-action="Delete" asp-route-id="@deviceModel.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                new PagedListRenderOptions
                {
                LiElementClasses = new string[] { "page-item" },
                PageClasses = new string[] { "page-link" },
                UlElementClasses = new string[] { "pagination", "float-right" }
                })
            </div>
        </div>
    </div>
</div>