Dashboard/ViewModels/ManufacturerViewModel.cs
namespace Dashboard.ViewModels
{
    public class ManufacturerViewModel : BaseViewModel
    {
        public string Name { get; set; }
        public ICollection<ProviderViewModel> Providers { get; set; }
        public ICollection<DeviceModelViewModel> Models { get; set; }
    }

    public class CreateManufacturerViewModel 
    {
        public string Name { get; set; }
        public string ProviderId { get; set; }
    }
    public class UpdateManufacturerViewModel
    {
        public string Name { get; set; }
        public string ProviderId { get; set; }

    }
}

Dashboard/Controllers/ManufacturersController.cs
using AutoMapper;
using Core;
using Core.Entities;
using Dashboard.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace Dashboard.Controllers
{
    public class ManufacturersController : Controller
    {

        private readonly DBContext _context;
        private readonly IMapper _mapper;
        public ManufacturersController(DBContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }


        // GET: ManufacturersController
        public async Task<ActionResult> Index(int? Page)
        {
            ViewBag.Title = "Manufactureres";
            var Manufactureres = await _context.Manufacturers
                .Include(m => m.Provider)
                .ToListAsync();
            return View(Manufactureres.ToPagedList(Page ?? 1, 10));
        }

        // GET: ManufacturersController/Details/5
        //public ActionResult Details(string id)
        //{
        //    return View();
        //}

        // GET: ManufacturersController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.Providers = await _context.Providers.ToListAsync();
            return View();
        }

        // POST: ManufacturersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateManufacturerViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var manufacturer = _mapper.Map<Manufacturer>(model);
                    await _context.Manufacturers.AddAsync(manufacturer);
                    var result = await _context.SaveChangesAsync();
                    if (result > 0)
                    {
                        TempData["SuccessMessage"] = $"<strong>Congrats!</strong>, {manufacturer.Name} has been added successfully";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Providers = await _context.Providers.ToListAsync();
                        ViewBag.Title = "Add new Manufacturer";
                        ViewBag.ErrorMessage = $"<strong>Sorry!</strong>, We had some trouble adding the manufacturer {manufacturer.Name}, please contact Administrator";
                        return View(model);
                    }
                }
                ViewBag.Providers = await _context.Providers.ToListAsync();
                return View(model);
            }
            catch (Exception e)
            {
                ViewBag.Providers = await _context.Providers.ToListAsync();
                ViewBag.ErrorMessage = $"<strong>OOOP!</strong>, We had some trouble adding the manufacturer, please contact Administrator";
                return View(model);
            }
        }

        // GET: ManufacturersController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var manufacturer = await _context.Manufacturers.FindAsync(id);
            if (manufacturer == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var model = _mapper.Map<UpdateManufacturerViewModel>(manufacturer);
            ViewBag.Providers = await _context.Providers.ToListAsync();
            ViewBag.Title = $"Edit {manufacturer.Name}";
            return View(model);
        }

        // POST: ManufacturersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, UpdateManufacturerViewModel model)
        {
            try
            {
                var manufacturer = await _context.Manufacturers.FindAsync(id);
                if (manufacturer == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                _mapper.Map(model, manufacturer);
                _context.Update(manufacturer);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                {
                    TempData["SuccessMessage"] = $"<strong>Success!</strong>, Changes on {manufacturer.Name} has been saved successfully";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View(model);
            }
        }

        // GET: ManufacturersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ManufacturersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Dashboard/Views/Manufacturers/Create.cshtml
@model CreateManufacturerViewModel
@{
    List<Provider> providers = ViewBag.Providers;
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <form asp-controller="Manufacturers" asp-action="Create" method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input type="text" class="form-control" asp-for="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label>Select Provider</label>
                        <select asp-for="ProviderId" class="form-control" >
                         <option>Select provider</option>
                            @foreach(var provider in providers)
                            {
                                <option value="@provider.Id">@provider.Name</option>
                            }
                        </select>
                      </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary  float-right  ml-1">Submit</button>
                    <a class="btn btn-danger  float-right" asp-controller="Manufacturers" asp-action="Index">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Dashboard/Views/Manufacturers/Edit.cshtml
@model UpdateManufacturerViewModel
@{
    List<Provider> providers = ViewBag.Providers;
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <form asp-controller="Manufacturers" asp-action="Edit" method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input type="text" class="form-control" asp-for="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label>Select Provider</label>
                        <select asp-for="ProviderId" class="form-control">
                            <option>Select provider</option>
                            @foreach (var provider in providers)
                            {
                                <option value="@provider.Id">@provider.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary  float-right  ml-1">Submit</button>
                    <a class="btn btn-danger  float-right" asp-controller="Manufacturers" asp-action="Index">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Dashboard/Views/Manufacturers/Index.cshtml
@model IPagedList<Manufacturer>
@{
    
}
<div class="row">
    <div class="col-12">
        @if (TempData["SuccessMessage"] != null && TempData["SuccessMessage"].ToString() != "")
        {
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @Html.Raw( @TempData["SuccessMessage"])
            </div>
        }
        <div class="card">
            <div class="card-header">
                <div class="card-tools">
                    <a asp-controller="manufacturers" asp-action="Create" class="btn btn-block btn-primary"><i class="fa fa-plus"></i> Add new</a>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Provider</th>
                            <th>Created By</th>
                            <th>Created At</th>
                            <th>Modified By</th>
                            <th>Modified At</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Manufacturer manufacturer in Model)
                        {
                            <tr>
                                <td>@manufacturer.Name</td>
                                <td>@(manufacturer.Provider == null? "" : manufacturer.Provider.Name)</td>
                                <td>@manufacturer.CreatedBy</td>
                                <td>@manufacturer.CreatedAt</td>
                                <td>@manufacturer.ModifiedBy</td>
                                <td>@manufacturer.ModifiedAt</td>
                                <td>
                                    <a asp-controller="manufacturers" asp-action="Edit" asp-route-id="@manufacturer.Id" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                    <a asp-controller="manufacturers" asp-action="Delete" asp-route-id="@manufacturer.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                new PagedListRenderOptions
                {
                LiElementClasses = new string[] { "page-item" },
                PageClasses = new string[] { "page-link" },
                UlElementClasses = new string[] { "pagination", "float-right" }
                })
            </div>
        </div>
    </div>
</div>